---
# Configuration

apt_packages:
  - curl
  - gcc
  - make
  - nmap
  - wget
  - build-essential
  - software-properties-common
  - net-tools
  - openjdk-11-jdk
  - openjdk-11-jre
  - keepassx
  - filezilla
  - inkscape
  - sketch
  - pandoc
#  - { name: docker, version: '1.5*' }
#  - docker-compose
  - git
  - htop
  - iotop
  - net-tools
  - coreutils
  - dos2unix
  - libnss3-tools
  - maven
#for docker
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - ufw
  - unattended-upgrades
  - jq
  

nodejs_version: 12.x
docker_version: 5:18.x

npm_packages:
  - http-server
  - typescript
  - karma-cli
  - browserify
  - webpack
  - bower
  - grunt
  - gulp-cli
  - less
  - react
  - react-redux
  - react-i18next
  - react-bootstrap
  - react-axios
  

##############################################
proxy_url: "http://proxy.cssf.lu:8080"
proxy_env:
  http_proxy: "{{ proxy_url }}"
  https_proxy: "{{ proxy_url }}"
  HTTPS_PROXY: "{{ proxy_url }}"
  HTTP_PROXY: "{{ proxy_url }}"
  no_proxy: "127.0.0.1,localhost,.cssf.lu"
  NO_PROXY: "127.0.0.1,localhost,.cssf.lu"
group_ips: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | difference([' ', '']) | join(',') }}"  

##############################################
timezone: "Europe/Luxembourg"
ntp_servers:
  - timeserv.cssf.lu

  
#############################################
ansible_managed: "This file is managed by ansible !!!!!!!!!!!!!!!!!!!" 