---
# Configuration

apt_packages:
#dev
  - curl
  - gcc
  - make
  - nmap
  - wget
  - vim
  - build-essential
  - software-properties-common
  - net-tools
  - openjdk-11-jdk
  - openjdk-11-jre
  - maven
  - gradle
#tools
  - keepassx
  - filezilla
  - inkscape
  - sketch
  - pandoc
  - aptitude
  - git
  - libxml2-utils
  - wireshark
# system tools
  - htop
  - iotop
  - iftop
  - net-tools
  - coreutils
  - dos2unix
  - libnss3-tools
  - lsof
  - tcpdump
# terminal
  - whois
  - zsh
  - colordiff
  - screen
  - tmux
  - terminator
#for docker
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - ufw
  - unattended-upgrades
  - jq
# ansible dependencies
  - python3-openssl
  - python-openssl
  - python-requests
  - python3-requests
  - python-docker
#for the example of pinning version
#  - { name: passwd, version: '1:4.5-1ubuntu1' }


nodejs_version: 12.x
docker_version: 5:18.x

npm_packages:
  - http-server
  - typescript
  - karma-cli
  - browserify
  - webpack
  - bower
  - grunt
  - gulp-cli
  - less
  - react
  - react-redux
  - react-i18next
  - react-bootstrap
  - react-axios
 

pip3_packages:
  - pipenv
  - numpy
  - scipy
  - pandas
  - cython
  - h5py
  - scikit-learn
  - requests
  - matplotlib
  - nose
  - jupyter
  - jupyterlab
  - beautifulsoup4
  - jinja2
  - fabric
  - docker-compose

umake_ide_packages:
  - eclipse-jee
  - idea-ultimate
  - atom

#


#############################################
proxy_url: "http://proxy.cssf.lu:8080"
proxy_env:
  http_proxy: "{{ proxy_url }}"
  https_proxy: "{{ proxy_url }}"
  HTTPS_PROXY: "{{ proxy_url }}"
  HTTP_PROXY: "{{ proxy_url }}"
  no_proxy: "127.0.0.1,localhost,.cssf.lu,10.0.0.0/8"
  NO_PROXY: "127.0.0.1,localhost,.cssf.lu,10.0.0.0/8"
group_ips: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | difference([' ', '']) | join(',') }}"

##############################################
timezone: "Europe/Luxembourg"
ntp_servers:
  - timeserv.cssf.lu


##############################################
# Default users
#############################################
users:
  - name:  create "{{ local_user }}"
    username: "{{ local_user }}"
    comment: local user for "{{ local_user }}"
    groups: [sudo, docker]
    use_sudo: yes
    
     
  - name: "Security User"
    username: security
    comment: Security User
    groups: ['sudo', 'security']
    uid: 1042
    home: /tmp/security
    password: $6$Vx5eI9dypWT0MSfT$d2Wr0aZhB8P.EX3b3s/Ns8pbmEwlvKV2XSC1qQvnVpj/.A.V8kxwXEf4KIsBd1h0.4BkUPR3fizdmIzaWrmFo/
    system: yes
    use_sudo: yes
    use_sudo_nopass: yes  


#######
# ssh conf via willshersystems.sshd
########
sshd:
  ClientAliveInterval: 60
  Compression: true
  PrintMotd: true
  PasswordAuthentication: true #for now


################################
# Ubuntu version
################################
ubuntu_target_version: "19.04"


