---
# Install & Configure Common Tools

- name: APT update cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600

- name: Create `/usr/share/man/man1` directory (required for Java 8)
  file:
    path: /usr/share/man/man1
    state: directory
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_release == 'bionic'
  become: true

- name: Install common tools
  apt:
    pkg: "{{ item.name | default(item) }}{{ '=' + item.version if (item.version | default(False)) else '' }}"
    state: "{{ 'present'  if (item.version | default(False)) else 'latest' }}"
    force: yes
  with_items: "{{ apt_packages | default([]) }}"
  become: true
  
  
- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
