---
# Install & Configure vscode

- name: Add public key
  apt_key: url="{{ vscode_ppa_key }}" id="{{ vscode_ppa_id }}" state=present
  become: true

- name: Add vscode repository
  apt_repository: repo="{{ vscode_ppa }}" state=present
  become: true

- name: Install latest vscode package
  apt: 
    name: "{{ packages }}" 
    state: latest
    update-cache: yes
  vars:
    packages: 
    - code
  become: true