---

- name: Install python
  apt: 
    name: "{{ packages }}"
    state: latest
    force: yes
  vars:
    packages:
    - python3
    - python3-pip
    - python
    - python-pip
    - python3-jmespath
    - python3-setuptools
  become: true

# Install Pip packages

- include: pip2.yml
- include: pip3.yml
