---
######
# packages facts
######
- name: Gather package facts
  package_facts:
    manager: auto

##########################################
#   NTP client conf
##########################################
- name: set timezone
  timezone:
    name: "{{ timezone }}"


- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
    force: no
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started

#############################################
# Proxy conf
#############################################
- name: env var for proxy in /etc/environment
  lineinfile:
    dest: /etc/environment
    line: "{{ item.key }}={{ item.value }}"
  loop:  "{{ proxy_env | dict2items  }}" 
  
############################################
# foreman config
############################################
- name: activate foreman callback in ansible.cfg
  blockinfile:
    path: /etc/ansible/ansible.cfg
    create: yes
    block: |
      [defaults]
      callback_whitelist = foreman
      [callback_foreman]
      url = "{{ foreman_url }}"
      ssl_cert = /etc/foreman-proxy/ssl_cert.pem
      ssl_key = /etc/foreman-proxy/ssl_key.pem
      verify_certs = /etc/foreman-proxy/ssl_ca.pem
  when: foreman_url is defined
 

    