---
######
# packages facts
######
- name: Gather package facts
  package_facts:
    manager: auto


##############
# username check
##############
- name: username var is present
  fail: msg="Bailing out. this play requires 'username'"
  when: username is not defined


##################
# hostname
##################
- name: pc_name var is present
  fail: msg="Bailing out. this play requires 'pc_name'"
  when: pc_name is not defined

- name: Change hostname
  hostname:
    name: "{{ pc_name }}"



##########################################
#   NTP client conf
##########################################
- name: set timezone
  timezone:
    name: "{{ timezone }}"


- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
    force: no
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started

#############################################
# Proxy conf
#############################################
- name: env var for proxy in /etc/environment
  lineinfile:
    dest: /etc/environment
    line: "{{ item.0 }}={{ item.1 }}"
  loop:  "{{ proxy_env | dictsort  }}"


##############################################
# vim config
#############################################
- name: Install vim if needed
  apt:
    name: vim
    state: present


- name: ensure /etc/vim/vimrc.local
  file:
    path: /etc/vim/vimrc.local
    state: touch
    mode: 0644

- name: VI - Syntax Highliting / Disable weird mouse + arrow behavior /Enable last position when reopening
  blockinfile:
    path: /etc/vim/vimrc.local
    create: yes
    marker: "\"# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      " Enable syntax highlighting
      syn on
      " Enable last position when reopening
      if has("autocmd")
        au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
      endif
      " Disable weird mouse +arrow  behavior
      set mouse=r
      set nocompatible





#############################################
## foreman config
#############################################
#
#- name: Add public key
#  apt_key:
#    url: "{{ foreman_ppa_key }}"
#    id: "{{ foreman_ppa_id }}"
#    state: present
#  become: true
#  when: foreman_url is defined
#
#- name: Add foreman repository
#  apt_repository:
#    repo: "{{ foreman_ppa }}"
#    state: present
#  become: true
#  when: foreman_url is defined
#
#- name: Install  ruby-foreman-discovery package
#  apt:
#    name: "{{ packages }}"
#    state: present
#    update-cache: yes
#  vars:
#    packages:
#    - "ruby-foreman-discovery"
#  become: true
#  when: foreman_url is defined
#
#- name: activate foreman callback in ansible.cfg
#  blockinfile:
#    path: /etc/ansible/ansible.cfg
#    create: yes
#    block: |
#      [defaults]
#      callback_whitelist = foreman
#      [callback_foreman]
#      url = "{{ foreman_url }}"
#      ssl_cert = /etc/foreman-proxy/ssl_cert.pem
#      ssl_key = /etc/foreman-proxy/ssl_key.pem
#      verify_certs = /etc/foreman-proxy/ssl_ca.pem
#  when: foreman_url is defined
#  become: true
#

