- name: Install Common Development Tools
  hosts: 127.0.0.1
  connection: local
  roles:
    - { role: role_base, tags: [ base, cert ] }
    - { role: role_apt, tags: apt }
    - { role: role_python, tags: python }
    - chromium
    - { role: role_docker, tags: docker}
    - { role: role_vscode, tags: vscode}
    - { role: role_ca-cert, tags: cert }
    - { role: role_users, ignore_errors: yes, tags: users }
    - { role: role_git_hook, tag: git_hook }
  tasks:
     - name: Reboot 
       reboot:
  become_user: root
  become: true
  environment: "{{ proxy_env }}"
