- name: Install Common Development Tools
  hosts: all
  roles:
    - { role: role_base, tags: [ base, cert ] }
    - { role: role_apt, tags: apt }
    - { role: role_python, tags: python }
    - role_chromium
    - { role: role_docker, tags: docker}
    - { role: role_vscode, tags: vscode}
    - { role: role_ca-cert, tags: cert }
    - { role: role_users, ignore_errors: yes, tags: users }
      # - { role: role_git_config, tag: git_config }
  become_user: root
  become: true
  environment: "{{ proxy_env }}"
