- name: Install Common Development Tools
  hosts: 127.0.0.1
  connection: local
  roles:
    - { role: role_base, tags: [ base, cert ] }
    - { role: apt, tags: apt }
    - { role: python, tags: python }
    - chromium
    - { role: docker, tags: docker}
    - { role: vscode, tags: vscode}
    - { role: ca-cert, tags: cert }
    - { role: role_users, ignore_errors: yes, tags: users }
    - { role: role_umake, tags: umake}
    - { role: role_git_hook, tags: git_hook }
 
    #External Roles need proxy to be set   
    - { role: chaosmail.nodejs, tags: nodejs  }
    - { role: willshersystems.sshd, tags: sshd }
    
    - { role: role_ubuntu_upgrade, tags: upgrade, 
           when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != ubuntu_target_version and  ubuntu_target_version is defined  } 
  become_user: root
  become: true
  environment: "{{ proxy_env }}"