- name: Install Common Development Tools
  hosts: all
  roles:
    - { role: role_base, tags: [ base, cert ] }
    - { role: role_apt, tags: apt }
    - { role: role_python, tags: python }
    - role_chromium
    - { role: role_docker, tags: docker}
    - { role: role_vscode, tags: vscode}
    - { role: role_ca-cert, tags: cert }
    - { role: role_users, ignore_errors: yes, tags: users }
    - { role: role_umake, tags: umake}
      #    - { role: role_git_config, tags: git_config }
    # - { role: role_foreman_cb, tags: foreman_cb}
    #External Roles need proxy to be set
    - { role: chaosmail.nodejs, tags: nodejs  }
    - { role: willshersystems.sshd, tags: sshd }


    - { role: role_ubuntu_upgrade, tags: upgrade,
           when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != ubuntu_target_version and  ubuntu_target_version is defined  }
  become_user: root
  become: true
  environment: "{{ proxy_env }}"
